
 
记录时间：2015-10-27 11:11:38,309 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：sddsew
 

 
记录时间：2015-10-27 11:20:38,111 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,140 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,140 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,140 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,141 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,141 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,142 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,142 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,142 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,142 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,143 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,143 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,143 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,144 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,144 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,144 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,145 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,145 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,145 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,145 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,146 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,146 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,146 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,147 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,147 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,147 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,148 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,148 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,148 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,149 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,149 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,149 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,150 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,150 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,150 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,150 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,151 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,151 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,151 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,152 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,152 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,152 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,153 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,153 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,153 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,154 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,154 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,154 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,154 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,155 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,155 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,155 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,156 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,156 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,156 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,157 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,157 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,157 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,158 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,158 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,158 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,158 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,159 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,159 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,159 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,160 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,160 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,160 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,161 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,161 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,161 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,161 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,162 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,162 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,162 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,163 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,163 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,163 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,164 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,164 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,164 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,165 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,165 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,165 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,166 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,166 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,166 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,166 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,167 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,167 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,167 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,168 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,168 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,168 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,169 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,169 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,169 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,170 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,170 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常

 
记录时间：2015-10-27 11:20:38,170 
线程ID:[1] 
日志级别：  ERROR 
出错类：Log4Net_Test.Program property: [(null)] - 
错误描述：error
 
System.Exception: 发生了一个异常
